version: '3'

services:
  shellyscan:
    build: .
    volumes:
      - data:/usr/src/myapp/
    environment:
      - INTERVAL=604800 # Default interval of 7 days in seconds
    network_mode: host
volumes:
  data:
